name: Continous integration

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '*'

permissions:
  checks: write
  pull-requests: write # only required if `comment: true` was enabled

jobs:
  checkout:
    runs-on: ubuntu-latest

    name: 'Install, lint and test'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Javascript'
        uses: ./.github/actions/setup-project

      - name: 'Lint'
        run: deno task lint

      - name: 'Test'
        run: deno task test --junit-path=./junit-report.xml

      - name: 'Publish test results'
        uses: mikepenz/action-junit-report@v5
        if: success()
        with:
          report_paths: '**/junit-report.xml'
          comment: true
